#!/bin/bash

### WCR
#visualize.py configExtrapoSignalControlRegion/htautau_lephad_wcr_reweight_mc16a.cfg
#visualize.py configExtrapoSignalControlRegion/htautau_lephad_wcr_reweight_mc16c.cfg

#visualize.py configExtrapoSignalControlRegion/htautau_lephad_wcr_reweight_wjets_mc16a.cfg
#visualize.py configExtrapoSignalControlRegion/htautau_lephad_wcr_reweight_wjets_mc16c.cfg

#visualize.py configExtrapoSignalControlRegion/htautau_lephad_wcr_reweight_qcd_mc16a.cfg
#visualize.py configExtrapoSignalControlRegion/htautau_lephad_wcr_reweight_qcd_mc16c.cfg

#visualize.py configExtrapoSignalControlRegion/htautau_lephad_wcr_reweight_wjetsqcd_mc16a.cfg
#visualize.py configExtrapoSignalControlRegion/htautau_lephad_wcr_reweight_wjetsqcd_mc16c.cfg


### TCR
#visualize.py configExtrapoSignalControlRegion/htautau_lephad_tcr_reweight_mc16a.cfg
#visualize.py configExtrapoSignalControlRegion/htautau_lephad_tcr_reweight_mc16c.cfg

#visualize.py configExtrapoSignalControlRegion/htautau_lephad_tcr_reweight_wjets_mc16a.cfg
#visualize.py configExtrapoSignalControlRegion/htautau_lephad_tcr_reweight_wjets_mc16c.cfg

#visualize.py configExtrapoSignalControlRegion/htautau_lephad_tcr_reweight_qcd_mc16a.cfg
#visualize.py configExtrapoSignalControlRegion/htautau_lephad_tcr_reweight_qcd_mc16c.cfg

#visualize.py configExtrapoSignalControlRegion/htautau_lephad_tcr_reweight_wjetsqcd_mc16a.cfg
#visualize.py configExtrapoSignalControlRegion/htautau_lephad_tcr_reweight_wjetsqcd_mc16c.cfg


### VR
visualize.py configExtrapoSignalControlRegion/htautau_lephad_vr_reweight_mc16a.cfg
visualize.py configExtrapoSignalControlRegion/htautau_lephad_vr_reweight_mc16c.cfg

#visualize.py configExtrapoSignalControlRegion/htautau_lephad_vr_reweight_wjets_mc16a.cfg
#visualize.py configExtrapoSignalControlRegion/htautau_lephad_vr_reweight_wjets_mc16c.cfg

#visualize.py configExtrapoSignalControlRegion/htautau_lephad_vr_reweight_qcd_mc16a.cfg
#visualize.py configExtrapoSignalControlRegion/htautau_lephad_vr_reweight_qcd_mc16c.cfg

#visualize.py configExtrapoSignalControlRegion/htautau_lephad_vr_reweight_wjetsqcd_mc16a.cfg
#visualize.py configExtrapoSignalControlRegion/htautau_lephad_vr_reweight_wjetsqcd_mc16c.cfg


### SR
#visualize.py configExtrapoSignalControlRegion/htautau_lephad_sr_reweight_mc16a.cfg
#visualize.py configExtrapoSignalControlRegion/htautau_lephad_sr_reweight_mc16c.cfg
